---
title: "DocumentTitle"
output: html_document
---
---
output:
  word_document: default
  pdf_document: default
  html_document: default
---
```{r load libraries}
library(randomForest)
library(caret)
library(nlme)
library(tictoc)
#library(e1071)
library(ipred)
library(gbm)
library(xlsx)
library(ranger)
#install.packages("party", dependencies = TRUE)
#library(party)
```


```{r}
# Reads your input as csv file
file <- read.csv("/location/filename.csv")
str(file)
```

```{r}

# random Partition
set.seed(223)
ind <- sample(2, nrow(random), replace = TRUE, prob = c(0.8, 0.2))
train <- file[ind==1,]
test <- file[ind==2,]
```
```{r}
tic()
# Random Forest
library(randomForest)
set.seed(5)
rf <- randomForest(FirstColumnName ~., data=train,
                   na.action = na.exclude,
                   ntree = 500,
                   mtry = 2,
                   importance = TRUE,
                   proximity = TRUE)
toc()
print(rf)
attributes(rf)
varImpPlot(rf)

```
```{r 5 fold cross validation & tuning with gbm }
set.seed(100)
tic()
rf2<- trainControl(
                method = "repeatedcv",
                number = 5,
                repeats = 1
)

set.seed(1)
fit <- train(FirstColumnName~., data= test,
             na.action = na.exclude,
             method = "gbm",
             trControl = rf2,
             verbose=FALSE)
  
toc()
fit
fit$bestTune
```

```{r}
ggplot(fit)
```
```{r }
s <- rf$mse
c <- rf$predicted

plot(s,c)
```
```{r}
#to write training, tested and predicted to xlsx file
write.xlsx(train, "/location/filename_training.xlsx")
write.xlsx(test,"/location/filename_testing.xlsx")
write.xlsx(rf$predicted,"/location/filename_predicted.xlsx")

```

```{r}
set.seed(123)
OOB_RMSE <- vector(mode= "numeric", length=100)

for (i in seq_along(OOB_RMSE)){
  optimal_ranger <- ranger(
    formula= ColumnName~.,
    data = train, 
    num.trees = 500, 
    mtry= 24,
    min.node.size = 5,
    sample.fraction = .8,
    importance = 'impurity'
    
  )
  OOB_RMSE[i] <- sqrt(optimal_ranger$prediction.error)
}
hist(OOB_RMSE, breaks = 20)
```

```{r}
###do NOT RUN
library(caret)
p1 <- predict(rf, train)
confusionMatrix(p1, train)

# # Prediction & Confusion Matrix - test random
p2 <- predict(rf, test)
confusionMatrix(p2, test$ColumnInterest)

```

```{r}
# Error rate of Random Forest
plot(rf)
```

```{r}
# No. of nodes for the trees
hist(treesize(rf),
     main = "No. of Nodes for the Trees",
     col = "red")
```
